### ISSUE TITLE
character.lua: Set clothing_character to default

### ISSUE THREAD

**Issue by bell07** [sfence/clothing#13]
Found this peace of code in character.lua that may causes problems
There is an assumption the default character is format 1.0 Sam.

```
      if minetest.settings:get_bool("clothing_character", true) then
        local default_skin_obj = skins.get(skins.default)
        default_skin_obj:set_texture("clothing_character_male.png")
      end
```

I think the default character should be set by

```
      if minetest.settings:get_bool("clothing_character", true) then
             skins.default = "clothing_skin"
      end
```

If sam should be hidden, you can loop trough `skins.meta`and adjust in_inventory_list attribute for skins you do not like to see

**Comment by sfence** [comment]
Thanks for the review.
Should be fixed by b693427.
