### ISSUE TITLE
bug report: cape position is wrong

### ISSUE THREAD

**Issue by superfloh247** [sfence/clothing#3]
The clothing cape appears in fron of the player, not on the back

minetest and minetest_game latest master, clothing latest v2 branch, all other mods latest master

world 1 (pink cape)
![Bildschirmfoto 2021-05-26 um 11 42 52](https://user-images.githubusercontent.com/26180993/119639387-d7dc5b00-be17-11eb-807d-0c432de4ddae.png)
load_mod_xocean = true
load_mod_x_farming = true
load_mod_underch = true
load_mod_skinsdb = true
load_mod_mobkit = true
load_mod_petz = true
load_mod_regional_weather = true
load_mod_mesecons_torch = true
load_mod_trunks = true
load_mod_bushes_classic = true
load_mod_moreores = true
load_mod_mob_horse = true
load_mod_moretrees = true
load_mod_moon_phases = true
load_mod_agriculture = true
load_mod_better_fauna = true
load_mod_mesecons_wires = true
load_mod_bushes = true
load_mod_mesecons_solarpanel = true
load_mod_mesecons_pressureplates = true
load_mod_mesecons_powerplant = true
load_mod_3d_armor = true
load_mod_mesecons_mvps = true
load_mod_mesecons_movestones = true
load_mod_homedecor_roofing = true
load_mod_mesecons_materials = true
load_mod_mesecons_pistons = true
load_mod_mesecons_gates = true
load_mod_mesecons_extrawires = true
load_mod_homedecor_furniture = true
load_mod_mesecons_doors = true
load_mod_mesecons_detector = true
load_mod_mesecons_receiver = true
load_mod_mesecons_delayer = true
load_mod_mesecons_button = true
load_mod_tubelib2 = true
load_mod_mesecons = true
load_mod_mesecons_switch = true
load_mod_lightning = true
load_mod_homedecor_windows_and_treatments = true
load_mod_flowers_plus = true
load_mod_water_life = true
load_mod_homedecor_tables = true
load_mod_mesecons_walllever = true
load_mod_3d_armor_sfinv = true
load_mod_display_api = true
load_mod_climate_api = true
load_mod_nature_classic = true
load_mod_ferns = true
load_mod_homedecor_common = true
load_mod_algae = true
load_mod_font_api = true
load_mod_x_bows = true
load_mod_animalworld = true
load_mod_along_shore = true
load_mod_gardens = true
load_mod_cavestuff = true
load_mod_extra_biomes = true
load_mod_hedges = true
load_mod_3d_plants = true
load_mod_mesecons_microcontroller = true
load_mod_gates_long = true
load_mod_farming = true
load_mod_signs_api = true
load_mod_mobs = true
load_mod_junglegrass = true
load_mod_signs_road = true
load_mod_youngtrees = true
load_mod_headanim = true
load_mod_mokapi = true
load_mod_cottages = true
load_mod_basic_materials = true
load_mod_beautiflowers = true
load_mod_mobs_animal = true
load_mod_compost = true
load_mod_luxury_decor = true
load_mod_draconis = true
load_mod_bows = true
load_mod_aquaz = true
load_mod_wieldview = true
load_mod_biome_lib = true
load_mod_shields = true
load_mod_ethereal = true
load_mod_ambience = true
load_mod_3dmushrooms = true
load_mod_footprints = true
load_mod_mesecons_stickyblocks = true
load_mod_mob_core = true
load_mod_unifieddyes = true
load_mod_people = true
load_mod_nativevillages = true
load_mod_auroras = true
load_mod_mobs_turtles = true
load_mod_mobs_jellyfish = true
load_mod_mobs_fish = true
load_mod_mesecons_carts = true
load_mod_willow = true
load_mod_plumtree = true
load_mod_pineapple = true
load_mod_maple = true
load_mod_mahogany = true
load_mod_larch = true
load_mod_ebony = true
load_mod_clementinetree = true
load_mod_chestnuttree = true
load_mod_cherrytree = true
load_mod_bamboo = true
load_mod_baldcypress = true
load_mod_birch = true
load_mod_pomegranate = true
load_mod_jacaranda = true
load_mod_lemontree = true
load_mod_oak = true
load_mod_palm = true
load_mod_hollytree = true
load_mod_tubelib = true
load_mod_mg_villages = true
load_mod_handle_schematics = true
load_mod_witches = true
load_mod_tubelib_addons1 = true
load_mod_tubelib_addons3 = true
load_mod_tubelib_addons2 = true
load_mod_gravelsieve = true
load_mod_builtin_item = true
load_mod_tt_base = true
load_mod_tt = true
load_mod_regrow = true
load_mod_islands = true
load_mod_cartographer_minetest_game = true
load_mod_cartographer = true
load_mod_inventorybags = true
load_mod_player_monoids = true
load_mod_crops = true
load_mod_toolranks = true
load_mod_playerphysics = true
load_mod_character_anim = true
load_mod_lumberjack = true
load_mod_modlib = true
load_mod_appliances = true
load_mod_clothing = true
load_mod_bonemeal = true
load_mod_qa_block = true 

world 2 (red cape):
![Bildschirmfoto 2021-05-25 um 16 26 03](https://user-images.githubusercontent.com/26180993/119639546-00645500-be18-11eb-966e-28e1c98b5a15.png)
load_mod_advtrains_train_japan = true
load_mod_advtrains_train_track = true
load_mod_advtrains_train_industrial = true
load_mod_advtrains_train_steam = true
load_mod_serialize_lib = true
load_mod_advtrains = true
load_mod_advtrains_train_subway = true
load_mod_mobs_animal = true
load_mod_farming = true
load_mod_mobs = true
load_mod_advtrains_itrainmap = true
load_mod_mob_horse = true
load_mod_xocean = true
load_mod_water_life = true
load_mod_skinsdb = true
load_mod_youngtrees = true
load_mod_woodsoils = true
load_mod_trunks = true
load_mod_molehills = true
load_mod_junglegrass = true
load_mod_flowers_plus = true
load_mod_ferns = true
load_mod_dryplants = true
load_mod_cottages = true
load_mod_along_shore = true
load_mod_basic_materials = true
load_mod_animalworld = true
load_mod_agriculture = true
load_mod_homedecor_kitchen = true
load_mod_3d_armor = true
load_mod_biome_lib = true
load_mod_homedecor_pictures_and_paintings = true
load_mod_unifieddyes = true
load_mod_better_fauna = true
load_mod_homedecor_furniture_medieval = true
load_mod_bows = true
load_mod_homedecor_office = true
load_mod_homedecor_tables = true
load_mod_cavestuff = true
load_mod_homedecor_fences = true
load_mod_nature_classic = true
load_mod_homedecor_seating = true
load_mod_shields = true
load_mod_extra_biomes = true
load_mod_homedecor_windows_and_treatments = true
load_mod_vines = true
load_mod_3d_armor_stand = true
load_mod_bale = true
load_mod_meseportals = true
load_mod_rocks = true
load_mod_bushes = true
load_mod_guinea_pig = true
load_mod_homedecor_lighting = true
load_mod_homedecor_electrical = true
load_mod_homedecor_roofing = true
load_mod_3dmushrooms = true
load_mod_building_blocks = true
load_mod_beautiflowers = true
load_mod_aquaz = true
load_mod_mobkit = true
load_mod_mokapi = true
load_mod_hedges = true
load_mod_homedecor_3d_extras = true
load_mod_homedecor_bedroom = true
load_mod_homedecor_books = true
load_mod_wieldview = true
load_mod_homedecor_clocks = true
load_mod_homedecor_cobweb = true
load_mod_bushes_classic = true
load_mod_homedecor_common = true
load_mod_homedecor_doors_and_gates = true
load_mod_compost = true
load_mod_homedecor_electronics = true
load_mod_3d_plants = true
load_mod_homedecor_exterior = true
load_mod_homedecor_foyer = true
load_mod_homedecor_furniture = true
load_mod_homedecor_gastronomy = true
load_mod_homedecor_misc = true
load_mod_homedecor_laundry = true
load_mod_moretrees = true
load_mod_homedecor_wardrobe = true
load_mod_itemframes = true
load_mod_gardens = true
load_mod_luxury_decor = true
load_mod_homedecor_bathroom = true
load_mod_mob_core = true
load_mod_petz = true
load_mod_fachwerk = true
load_mod_algae = true
load_mod_headanim = true
load_mod_advtrains_assets = true
load_mod_advtrains_platform = true
load_mod_tubelib2 = true
load_mod_signs_bot = true
load_mod_mesecons_wires = true
load_mod_mesecons_torch = true
load_mod_mesecons_switch = true
load_mod_mesecons_pressureplates = true
load_mod_mesecons_powerplant = true
load_mod_mesecons_noteblock = true
load_mod_mesecons_mvps = true
load_mod_mesecons_movestones = true
load_mod_mesecons_materials = true
load_mod_mesecons_pistons = true
load_mod_mesecons_hydroturbine = true
load_mod_mesecons_gates = true
load_mod_mesecons_extrawires = true
load_mod_mesecons_doors = true
load_mod_mesecons_detector = true
load_mod_mesecons_receiver = true
load_mod_mesecons_delayer = true
load_mod_mesecons_button = true
load_mod_mesecons_stickyblocks = true
load_mod_mesecons_walllever = true
load_mod_mesecons_solarpanel = true
load_mod_mesecons = true
load_mod_mesecons_microcontroller = true
load_mod_mesecons_insulated = true
load_mod_mesecons_lightstone = true
load_mod_regional_weather = true
load_mod_moon_phases = true
load_mod_lightning = true
load_mod_ambience = true
load_mod_climate_api = true
load_mod_wrench = true
load_mod_technic_worldgen = true
load_mod_technic_chests = true
load_mod_technic = true
load_mod_extranodes = true
load_mod_spacecannon = true
load_mod_concrete = true
load_mod_pipeworks = true
load_mod_x_bows = true
load_mod_x_farming = true
load_mod_gates_long = true
load_mod_morelights = true
load_mod_ilights = true
load_mod_morelights_modern = true
load_mod_morelights_extras = true
load_mod_morelights_vintage = true
load_mod_moretrains_vintage = true
load_mod_moretrains_steam = true
load_mod_moretrains_gondola = true
load_mod_moretrains_basic = true
load_mod_signs_api = true
load_mod_signs = true
load_mod_font_metro = true
load_mod_moretrains_japan = true
load_mod_moretrains_industrial = true
load_mod_display_api = true
load_mod_font_api = true
load_mod_boards = true
load_mod_signs_road = true
load_mod_steles = true
load_mod_moreores = true
load_mod_moarmour = true
load_mod_ethereal = true
load_mod_3d_armor_flyswim = true
load_mod_obsidianstuff = true
load_mod_techpack_stairway = true
load_mod_doc_identifier = true
load_mod_doc_basics = true
load_mod_doc = true
load_mod_doc_items = true
load_mod_unifiedbricks = true
load_mod_mask = true
load_mod_bike = true
load_mod_underch = true
load_mod_sailing = true
load_mod_pkarcs_doors3 = true
load_mod_pkarcs_doors = true
load_mod_fireworks_redo = true
load_mod_hyperloop = true
load_mod_bridger = true
load_mod_pkarcs = true
load_mod_draconis = true
load_mod_footprints = true
load_mod_boats = true
load_mod_people = true
load_mod_nativevillages = true
load_mod_greek = true
load_mod_portalgun = true
load_mod_scifi_nodes = true
load_mod_auroras = true
load_mod_mobs_turtles = true
load_mod_mobs_jellyfish = true
load_mod_mobs_fish = true
load_mod_mobs_crocs = true
load_mod_mobs_sharks = true
load_mod_paleotest = true
load_mod_metrosigns = true
load_mod_mesecons_carts = true
load_mod_willow = true
load_mod_plumtree = true
load_mod_pineapple = true
load_mod_maple = true
load_mod_mahogany = true
load_mod_larch = true
load_mod_ebony = true
load_mod_clementinetree = true
load_mod_chestnuttree = true
load_mod_cherrytree = true
load_mod_bamboo = true
load_mod_baldcypress = true
load_mod_birch = true
load_mod_hollytree = true
load_mod_lemontree = true
load_mod_oak = true
load_mod_pomegranate = true
load_mod_jacaranda = true
load_mod_palm = true
load_mod_snowball = true
load_mod_castle_weapons = true
load_mod_nether = true
load_mod_livingnether = true
load_mod_tubelib = true
load_mod_techpack_warehouse = true
load_mod_safer_lua = true
load_mod_lcdlib = true
load_mod_gravelsieve = true
load_mod_sl_controller = true
load_mod_tubelib_addons1 = true
load_mod_tubelib_addons3 = true
load_mod_tubelib_addons2 = true
load_mod_smartline = true
load_mod_handle_schematics = true
load_mod_new_campfire = true
load_mod_mg_villages = true
load_mod_builtin_item = true
load_mod_rocket = true
load_mod_tt_base = true
load_mod_tt = true
load_mod_regrow = true
load_mod_islands = true
load_mod_rangedweapons = true
load_mod_inventorybags = true
load_mod_glider = true
load_mod_minecart = true
load_mod_hopper = true
load_mod_chesttools = true
load_mod_digtron = true
load_mod_locks = true
load_mod_goblins = true
load_mod_player_monoids = true
load_mod_playerphysics = true
load_mod_crops = true
load_mod_toolranks = true
load_mod_modlib = true
load_mod_lumberjack = true
load_mod_character_anim = true
load_mod_appliances = true
load_mod_clothing = true
load_mod_bonemeal = true
load_mod_qa_block = true

**Comment by superfloh247** [comment]
I suspect character_anim, playerphysics or player_monoids.
I'll disable them one by one and test and give feedback.

**Comment by superfloh247** [comment]
It's character_anim.

load_mod_character_anim = false

![Bildschirmfoto 2021-05-26 um 12 09 01](https://user-images.githubusercontent.com/26180993/119642707-4a026f00-be1b-11eb-8dcc-326f4f1f76db.png)

![Bildschirmfoto 2021-05-26 um 12 09 31](https://user-images.githubusercontent.com/26180993/119642739-538bd700-be1b-11eb-8a36-9da7b34247ba.png)

**Comment by sfence** [comment]
Thanks for the feedback. I will try to find and solve this problem.

At the moment, you can use headanim mod instead of character_anim mod.

**Comment by superfloh247** [comment]
I had both mods active, headanim and character_anim - maybe that's my problem?

**Comment by sfence** [comment]
> I had both mods active, headanim and character_anim - maybe that's my problem?

Probably not. I tested it with headanim only, and it is ok. With disabled headanim and enabled character_anim I see the problem.
It looks like character_anim override character model from skinsdb. I am trying to solve it with the author of character_anim mod ([forum topic](https://forum.minetest.net/viewtopic.php?f=9&t=25385) ).

I think that the functionality of headanim mod is included in character_anim mod. So it is probably useless to use headanim and character_anim at same time.

**Comment by appgurueu** [comment]
> I think that the functionality of headanim mod is included in character_anim mod. So it is probably useless to use headanim and character_anim at same time.

Yes. The newest version of character anim probably fixes this, can you test?

**Comment by sfence** [comment]
Fixed with https://github.com/appgurueu/character_anim/issues/2

Closed. @superfloh247
