### ISSUE TITLE
wrong short sleeve on one arm

### ISSUE THREAD

**Issue by singularis-mzf** [sfence/clothing#8]
When the character is wearing shirt with short sleeve of any color, on the back side of the left arm the sleeve is displayed as long one. This also affects a mannequin stand.

**Comment by sfence** [comment]
I see the problem on the mannequin stand, but not on the player.
![screenshot_20220802_065500](https://user-images.githubusercontent.com/17455197/182294905-d0c7ac58-7e60-4da1-a35d-13e1c38452ad.png)

Can you add some screenshots and information about the mods, you are using?

**Comment by singularis-mzf** [comment]
I use 'clothing' with 'appliances' and 'skinsdb' (the newest commit from git: b76982); I also use dreambuilder\_hotbar, farming (redo) and unified\_inventory, but disabling of these three mods does not change the behaviour. I don't use 3d\_armor, however when I tried to enable it (the second screenshot is with 3d\_armor enabled), the problem persists.
![screenshot_20220802_150359](https://user-images.githubusercontent.com/46221138/182382484-23352a2d-d466-46fd-b073-008910fe3abc.png)

![screenshot_20220802_151708](https://user-images.githubusercontent.com/46221138/182384383-53e33db8-2482-47c1-b622-c2ca5b33efdf.png)

From your screenshot it seems that the player has a shirt with long sleeves (both sleeves look long). Those shirts are not affected; the problem affects only shirts with short sleeves (in the inventory they are called 'short' instead of 'shirt' - for example "pink-grey cotton **short** with short sleeve", I don't know if it's typing error or they are called that way somewhere).

**Comment by sfence** [comment]
Fixed with commit [c3b5208](https://github.com/sfence/clothing/commit/c3b52088559985ed4ed8ead18862cd7e98d2c63b)
