### ISSUE TITLE
no back side of clothes on the mannequin stand

### ISSUE THREAD

**Issue by singularis-mzf** [sfence/clothing#9]
The back side of the Mannequin stand does not display texture of the shirt, only a cape is displayed there. Maybe its necessary for more simple model of the stand, but for me it looks weird. I suggest to display the shirt there the same way as it is displayed on the player character.

**Comment by sfence** [comment]
This looks to be fixed with minetest 5.6.0. 

But I add mannequin model based on player model from 3d_armow_flyswim. So it should be fixed by this too.

Commit 3e27fdbf737f02eb20f66d0a9a009e415e50e584
